// <auto-generated />
using System;
using FikaForecast.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FikaForecast.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FikaDbContext))]
    [Migration("20260405114143_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FikaForecast.Domain.Entities.CategoryAssessment", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssessmentId");

                    b.HasIndex("ItemId");

                    b.ToTable("CategoryAssessments");
                });

            modelBuilder.Entity("FikaForecast.Domain.Entities.NewsBriefRun", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawAgentOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawMarkdownOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("RunId");

                    b.ToTable("NewsBriefRuns");
                });

            modelBuilder.Entity("FikaForecast.Domain.Entities.NewsItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("FikaForecast.Domain.Entities.WeeklySummaryRun", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoodSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetMood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawAgentOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawMarkdownOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("WeekEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("WeekStart")
                        .HasColumnType("TEXT");

                    b.HasKey("RunId");

                    b.ToTable("WeeklySummaryRuns");
                });

            modelBuilder.Entity("FikaForecast.Domain.Entities.WeeklySummaryTheme", b =>
                {
                    b.Property<Guid>("ThemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ThemeId");

                    b.HasIndex("RunId");

                    b.ToTable("WeeklySummaryThemes");
                });

            modelBuilder.Entity("FikaForecast.Domain.Entities.CategoryAssessment", b =>
                {
                    b.HasOne("FikaForecast.Domain.Entities.NewsItem", null)
                        .WithMany("Assessments")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FikaForecast.Domain.Entities.NewsItem", b =>
                {
                    b.HasOne("FikaForecast.Domain.Entities.NewsBriefRun", null)
                        .WithOne("Item")
                        .HasForeignKey("FikaForecast.Domain.Entities.NewsItem", "RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FikaForecast.Domain.Entities.WeeklySummaryTheme", b =>
                {
                    b.HasOne("FikaForecast.Domain.Entities.WeeklySummaryRun", null)
                        .WithMany("Themes")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FikaForecast.Domain.Entities.NewsBriefRun", b =>
                {
                    b.Navigation("Item");
                });

            modelBuilder.Entity("FikaForecast.Domain.Entities.NewsItem", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("FikaForecast.Domain.Entities.WeeklySummaryRun", b =>
                {
                    b.Navigation("Themes");
                });
#pragma warning restore 612, 618
        }
    }
}
